language: node_js
node_js:
        - "stable"
sudo: false
cache:
    - "node_modules"
    - apt

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            - default-jre
branches:
    only:
        - original_state
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - cd $TRAVIS_BUILD_DIR
    - curl -JLO http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
    - echo -e "#!/bin/sh\njava -jar $(pwd)/plantuml.jar" >> plantuml
    - chmod +x plantuml
    - export PATH="$PATH:$(pwd)"
    - cd tools/math_formula
    - npm i
    - chmod +x ../doxygen/extract.sh ../plantuml/gen.sh
    - cd $TRAVIS_BUILD_DIR

script:
    - cd tools/math_formula
    - npm run build
    - cd ../plantuml
    - bash -n ./gen.sh
    - cd ../doxygen
    - make

notifications:
    email: false
