language: node_js
node_js:
    - stable
    - lts/*
python:
    - '2.7'
sudo: required
cache:
  apt: true
  homebrew: true
  directories:
    - "$TRAVIS_BUILD_DIR/tools/math_formula/node_modules"
addons:
  apt:
    packages:
        - graphviz
        - default-jre
        - xvfb
  homebrew:
    packages:
        - graphviz
        - plantuml
    update: true
branches:
  only:
    - original_state
    - draft
    - master
    - "/^greenkeeper/.*$/"
os:
    - linux
    - osx
env:
    - DOXYGEN_VERSION=1.8.14

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CPU_NUM=`grep -c ^processor /proc/cpuinfo`; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CPU_NUM=`sysctl -n hw.logicalcpu_max`; fi
    - openssl aes-256-cbc -K $encrypted_0de92ec5cff5_key -iv $encrypted_0de92ec5cff5_iv -in travis_key.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git config --global user.email "falgon53@yahoo.co.jp"
    - git config --global user.name "falgon"
    - git config --global core.autocrlf "input"
    - pip install --user -U pip

install:
    - travis_retry wget http://ftp.stack.nl/pub/users/dimitri/doxygen-$DOXYGEN_VERSION.src.tar.gz
    - gunzip doxygen-$DOXYGEN_VERSION.src.tar.gz
    - tar xf doxygen-$DOXYGEN_VERSION.src.tar 
    - cd doxygen-$DOXYGEN_VERSION
    - mkdir build && cd build
    - cmake -G "Unix Makefiles" .. && make -j$CPU_NUM && sudo make install
    - cd $TRAVIS_BUILD_DIR
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -JLO http://sourceforge.net/projects/plantuml/files/plantuml.jar/download; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod 755 plantuml.jar; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo -e "#!/bin/bash\nxvfb-run java -splash:no -jar $(pwd)/plantuml.jar \"\$@\"" >> plantuml; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x plantuml; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$PATH:$(pwd)"; fi
    - cd tools/math_formula
    - npm i
    - chmod +x ../plantuml/gen.sh
    - cd $TRAVIS_BUILD_DIR
    - make setup_env

jobs:
  include:
    - stage: Deploy
      script:
        - if [ "$TRAVIS_BRANCH" = "draft" ]; then make BOOK_BRANCH=book_draft COMMIT_MESSAGE="by Travis CI (JOB $TRAVIS_JOB_NUMBER)" book; fi
        - if [ "$TRAVIS_BRANCH" = "master" ]; then make COMMIT_MESSAGE="by Travis CI (JOB $TRAVIS_JOB_NUMBER)" book; fi

notifications:
  email: false
