language: node_js
node_js:
        - "stable"
sudo: false
cache:
    apt: true
    directories:
        - "$TRAVIS_BUILD_DIR/tools/math_formula/node_modules"

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            - default-jre
            - xvfb
    homebrew:
        packages:
            - doxygen
            - graphviz
            - plantuml
            - xvfb
        update: true

branches:
    only:
        - original_state
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - cd $TRAVIS_BUILD_DIR
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -JLO http://sourceforge.net/projects/plantuml/files/plantuml.jar/download; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod 755 plantuml.jar; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo -e "#!/bin/bash\nxvfb-run java -splash:no -jar $(pwd)/plantuml.jar \"\$@\"" >> plantuml; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x plantuml; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$PATH:$(pwd)"; fi
    - cd tools/math_formula
    - npm i
    - chmod +x ../plantuml/gen.sh
    - cd $TRAVIS_BUILD_DIR

script:
    - cd $TRAVIS_BUILD_DIR/tools/plantuml && bash -n ./gen.sh && ./gen.sh
    - cd $TRAVIS_BUILD_DIR/tools/doxygen && bash -n ./extract.sh && make
    - cd $TRAVIS_BUILD_DIR/tools/math_formula && npm run build && npm run run

notifications:
    email: false
