language: node_js
node_js:
        - "stable"
sudo: false
cache:
    - "node_modules"
    - apt

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            - plantuml
branches:
    only:
        - original_state
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - cd tools/math_formula
    - npm i
    - chmod +x ../doxygen/extract.sh
    - chmod +x ../plantuml/gen.sh
    - cd $TRAVIS_BUILD_DIR

script:
    - cd tools/math_formula
    - npm run build
    - cd ../doxygen
    - make
    - cd ../plantuml
    - ./gen.sh

notifications:
    email: false
