language: node_js
node_js:
        - "stable"
sudo: false
cache:
    - "node_modules"
    - apt

addons:
    apt:
        packages:
            - doxygen
            - graphviz
branches:
    only:
        - original_state
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - cd tools/math_formula
    - npm i

jobs:
    include:
        - stage: Build math formula
          script:
              - cd tools/math_formula
              - npm run build
notifications:
    email: false
