language: node_js
node_js:
        - "stable"
        - 'lts/*'
python:
        - "2.7"

sudo: false
cache:
    apt: true
    homebrew: true
    directories:
        - "$TRAVIS_BUILD_DIR/tools/math_formula/node_modules"

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            - default-jre
            - xvfb
    homebrew:
        packages:
            - doxygen
            - graphviz
            - plantuml
        update: true

branches:
    only:
        - original_state
        - draft
        - master
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

before_install:
    - easy_install --version
    - pip freeze
    - travis_retry pip install -U setuptools
    - cd `mktemp -d`
    - travis_retry wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
    - travis_retry python get-pip.py
    - cd $OLDPWD
    - pip --version
    - easy_install --version

install:
    - cd $TRAVIS_BUILD_DIR
    - chmod +x  $TRAVIS_BUILD_DIR/travis/*.sh
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -JLO http://sourceforge.net/projects/plantuml/files/plantuml.jar/download; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod 755 plantuml.jar; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo -e "#!/bin/bash\nxvfb-run java -splash:no -jar $(pwd)/plantuml.jar \"\$@\"" >> plantuml; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x plantuml; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export PATH="$PATH:$(pwd)"; fi
    - cd tools/math_formula
    - npm i
    - chmod +x ../plantuml/gen.sh
    - cd $TRAVIS_BUILD_DIR
    - make setup_env

jobs:
    include:
        - stage: Running task
          script:
            - if [ "$TRAVIS_BRANCH" = "original_state" ]; then $TRAVIS_BUILD_DIR/travis/original_state.sh; fi
            - if [ "$TRAVIS_BRANCH" = "draft" ]; then make BOOK_BRANCH=book_draft; fi
            - if [ "$TRAVIS_BRANCH" = "master" ]; then make book; fi

notifications:
    email: false
