language: node_js
node_js:
        - "stable"
sudo: false
cache:
    apt: true
    directories:
        - "$TRAVIS_BUILD_DIR/tools/math_formula/node_modules"

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            - default-jre
            - xvfb
branches:
    only:
        - original_state
        - /^greenkeeper/.*$/
os:
    - linux
    - osx

install:
    - cd $TRAVIS_BUILD_DIR
    - curl -JLO http://sourceforge.net/projects/plantuml/files/plantuml.jar/download
    - chmod 755 plantuml.jar
    - echo -e "#!/bin/bash\nxvfb-run java -splash:no -jar $(pwd)/plantuml.jar \"\$@\"" >> plantuml
    - chmod +x plantuml
    - export PATH="$PATH:$(pwd)"
    - cd tools/math_formula
    - npm i
    - chmod +x ../plantuml/gen.sh
    - cd $TRAVIS_BUILD_DIR

script:
    - cd tools/math_formula && npm run build
    - cd ../plantuml && bash -n ./gen.sh && ./gen.sh
    - cd ../doxygen && bash -n ./extract.sh && make

jobs:
    include:
        - stage: Generate math formula
          script:
              - cd $TRAVIS_BUILD_DIR/math_formula
              - npm run run


notifications:
    email: false
